---
- name: Install Package on Windows(s)
  gather_facts: "yes"
  vars_files:
    - vars/windows.yml
  hosts: all
  tasks:
    - name: Install package
      win_chocolatey:
        name: "{{ windows_package_name }}"
        state: latest
