---
- name: Install Package on Windows(s)
  gather_facts: "yes"
  vars:
    ansible_connection: winrm
    ansible_become_method: runas
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_read_timeout_sec: 150
    ansible_winrm_operation_timeout_sec: 120
  hosts: all
  tasks:
    - name: Manage package
      win_chocolatey:
        name: "{{ windows_package_name }}"
        state: "{{ state }}"
