---
- name: "Master site play for Linux"
  hosts: tag_linux
  vars_files:
    - vars/vault
  roles:
    - common
    - linux
    - databases
    - webservers

- name: "Master site play for Windows"
  hosts: tag_windows
  vars_files:
    - vars/vault
    - vars/winrm.yml
  roles:
    - common
    - windows
