---
- name: "Master site play"
  hosts: all
  tasks:
    - name: "Import playbooks"
      import_playbook: everything.yml
      import_playbook: linux.yml
      import_playbook: windows.yml
      import_playbook: webservers.yml
