---
- name: "Master site play"
  hosts: all
  vars_files:
    - vars/vault
    - vars/windows.yml
    - vars/winrm.yml
    - windows_become.yml
  tasks:
    - debug:
      msg: "site.yml execution"

- name: import_playbook everything.yml
  import_playbook: everything.yml
- name: import_playbook linux.yml
  import_playbook: linux.yml
- name: import_playbook windows.yml
  import_playbook: windows.yml
- name: import_playbook webservers.yml
  import_playbook: webservers.yml
