---
- name: Patching Group2 (ubuntu)
  hosts: _managed_patching_group_group_2
  gather_facts: yes
  become: yes
  vars:
    - ansuble_ssh_user: ubuntu

  tasks:

    # Use a block to perform tasks conditionally—only if running Ubuntu 12.04.
    - block:

      # Now would be a good time to take a backup if you can trigger an
      # automated backup!

      - name: Upgrade all packages to the latest version
        apt: update_cache=yes upgrade=full

      - name: Ensure update-manager-core is installed.
        apt: name=update-manager-core state=present

      - name: Run do-release-upgrade non-interactively.
        command: do-release-upgrade -f DistUpgradeViewNonInteractive
        ignore_errors: true

      - name: Reboot the server.
        command: reboot
        async: 0
        poll: 0

      - name: Wait for server to reboot.
        wait_for:
          host: "{{ ansible_ssh_host }}"
          port: 22
          state: started
        connection: local
        become: no

      when: ansible_distribution == 'Ubuntu'
