---
# tasks file for windows
- name: Ensure user bob is present
  win_user:
    name: bob
    password: B0bP4ssw0rd
    state: present
    groups:
      - Users
- name: Install git
  win_chocolatey:
    name: git
    state: present
