---
- name: "print inventory hostname and uuid"
  debug:
    msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

- name: Configure SSH
  template:
    src: templates/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  notify:
    - restard sshd

- name: Create MOTD
  template:
    src: templates/issue.net
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644

- name: Generate MOTD role
  import_tasks: roles.yml
