- name: Set ENVIRONMENT in MOTD
  lineinfile:
    path: /etc/issue.net
    line: 'ENVIRONMENT: development'

- name: Add role COMMON to MOTD
  lineinfile:
    path: /etc/issue.net
    line: 'ROLE: common'
